name: my_project

packages:
  - packages/**
  - example/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  gen:
    run: melos exec -- dart pub run build_runner watch --delete-conflicting-outputs
    select-package:
      scope: "*example*"
