name: automapper_generator
description: A starting point for Dart libraries or applications.
version: 0.0.1

# homepage: https://www.example.com

environment:
  sdk: ">=2.18.7 <3.0.0"

# dependencies:
#   path: ^1.8.0
dependencies:
  automapper: ^0.0.1
  analyzer: ^5.4.0
  build: ^2.3.1
  code_builder: ^4.4.0
  path: ^1.8.3
  source_gen: ^1.2.6
  collection: ^1.17.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
  source_gen_test: ^1.0.4
  generator_test: ^0.2.0
